// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMessage struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type OpenFileMessage struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenFileMessage) Reset()         { *m = OpenFileMessage{} }
func (m *OpenFileMessage) String() string { return proto.CompactTextString(m) }
func (*OpenFileMessage) ProtoMessage()    {}
func (*OpenFileMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *OpenFileMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFileMessage.Unmarshal(m, b)
}
func (m *OpenFileMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFileMessage.Marshal(b, m, deterministic)
}
func (m *OpenFileMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFileMessage.Merge(m, src)
}
func (m *OpenFileMessage) XXX_Size() int {
	return xxx_messageInfo_OpenFileMessage.Size(m)
}
func (m *OpenFileMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFileMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFileMessage proto.InternalMessageInfo

func (m *OpenFileMessage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type OpenFileResponse struct {
	Version              int64    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenFileResponse) Reset()         { *m = OpenFileResponse{} }
func (m *OpenFileResponse) String() string { return proto.CompactTextString(m) }
func (*OpenFileResponse) ProtoMessage()    {}
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *OpenFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenFileResponse.Unmarshal(m, b)
}
func (m *OpenFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenFileResponse.Marshal(b, m, deterministic)
}
func (m *OpenFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenFileResponse.Merge(m, src)
}
func (m *OpenFileResponse) XXX_Size() int {
	return xxx_messageInfo_OpenFileResponse.Size(m)
}
func (m *OpenFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenFileResponse proto.InternalMessageInfo

func (m *OpenFileResponse) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type FileQuery struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileQuery) Reset()         { *m = FileQuery{} }
func (m *FileQuery) String() string { return proto.CompactTextString(m) }
func (*FileQuery) ProtoMessage()    {}
func (*FileQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *FileQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileQuery.Unmarshal(m, b)
}
func (m *FileQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileQuery.Marshal(b, m, deterministic)
}
func (m *FileQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileQuery.Merge(m, src)
}
func (m *FileQuery) XXX_Size() int {
	return xxx_messageInfo_FileQuery.Size(m)
}
func (m *FileQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FileQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FileQuery proto.InternalMessageInfo

func (m *FileQuery) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type FileListResponse struct {
	Filenames            []string `protobuf:"bytes,1,rep,name=filenames,proto3" json:"filenames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileListResponse) Reset()         { *m = FileListResponse{} }
func (m *FileListResponse) String() string { return proto.CompactTextString(m) }
func (*FileListResponse) ProtoMessage()    {}
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *FileListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileListResponse.Unmarshal(m, b)
}
func (m *FileListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileListResponse.Marshal(b, m, deterministic)
}
func (m *FileListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileListResponse.Merge(m, src)
}
func (m *FileListResponse) XXX_Size() int {
	return xxx_messageInfo_FileListResponse.Size(m)
}
func (m *FileListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileListResponse proto.InternalMessageInfo

func (m *FileListResponse) GetFilenames() []string {
	if m != nil {
		return m.Filenames
	}
	return nil
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "api.PingMessage")
	proto.RegisterType((*OpenFileMessage)(nil), "api.OpenFileMessage")
	proto.RegisterType((*OpenFileResponse)(nil), "api.OpenFileResponse")
	proto.RegisterType((*FileQuery)(nil), "api.FileQuery")
	proto.RegisterType((*FileListResponse)(nil), "api.FileListResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4a, 0xec, 0x30,
	0x10, 0x86, 0x5b, 0x7a, 0xd8, 0xd3, 0x8c, 0xa0, 0x65, 0x50, 0x28, 0x45, 0x70, 0x09, 0x08, 0x2b,
	0xc8, 0xb2, 0xa8, 0x37, 0xbe, 0x40, 0xf1, 0x42, 0x51, 0xbb, 0x4f, 0x10, 0x61, 0xac, 0x81, 0x9a,
	0x84, 0x4e, 0x14, 0xf6, 0x99, 0x7c, 0x49, 0x49, 0xd8, 0x54, 0x5d, 0xbd, 0xcb, 0xfc, 0xf9, 0x32,
	0xfc, 0x1f, 0x01, 0xa1, 0x9c, 0x5e, 0xba, 0xd1, 0x7a, 0x8b, 0x85, 0x72, 0x5a, 0x9e, 0xc1, 0xde,
	0x83, 0x36, 0xfd, 0x1d, 0x31, 0xab, 0x9e, 0xb0, 0x81, 0xb2, 0x1f, 0x89, 0xbc, 0x36, 0x7d, 0x9d,
	0xcf, 0xf3, 0x85, 0xe8, 0xa6, 0x59, 0x9e, 0xc2, 0xc1, 0xbd, 0x23, 0xd3, 0xea, 0x81, 0x12, 0x8e,
	0xf0, 0xcf, 0x29, 0xff, 0xb2, 0x45, 0xe3, 0x59, 0x9e, 0x43, 0x95, 0xb0, 0x8e, 0xd8, 0x59, 0xc3,
	0x84, 0x35, 0xfc, 0x7f, 0xa7, 0x91, 0xb5, 0x35, 0x11, 0x2d, 0xba, 0x34, 0xca, 0x13, 0x10, 0x81,
	0x7c, 0x7c, 0xa3, 0x71, 0xf3, 0xe7, 0xba, 0x15, 0x54, 0x01, 0xb8, 0xd5, 0xec, 0xa7, 0x75, 0xc7,
	0x20, 0x9e, 0xf5, 0x40, 0x46, 0xbd, 0x12, 0xd7, 0xf9, 0xbc, 0x58, 0x88, 0xee, 0x2b, 0xb8, 0xf8,
	0xc8, 0x61, 0xd6, 0x2a, 0xf6, 0xed, 0x1a, 0x57, 0x50, 0xae, 0xd5, 0xe6, 0x86, 0x86, 0xc1, 0x62,
	0xb5, 0x0c, 0xea, 0xdf, 0x64, 0x9b, 0x5f, 0x89, 0xcc, 0xf0, 0x1a, 0xca, 0xd4, 0x1e, 0x0f, 0xe3,
	0xfd, 0x8e, 0x73, 0x73, 0xf4, 0x23, 0x4d, 0x9d, 0x64, 0x86, 0x57, 0x20, 0x42, 0xcb, 0x90, 0x32,
	0xee, 0x47, 0x6a, 0x52, 0xdb, 0xbe, 0xda, 0x35, 0x91, 0xd9, 0xd3, 0x2c, 0x7e, 0xc6, 0xe5, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x70, 0x70, 0x51, 0x99, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FastFSClient is the client API for FastFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FastFSClient interface {
	SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
	OpenFile(ctx context.Context, in *OpenFileMessage, opts ...grpc.CallOption) (*OpenFileResponse, error)
	ListFiles(ctx context.Context, in *FileQuery, opts ...grpc.CallOption) (*FileListResponse, error)
}

type fastFSClient struct {
	cc *grpc.ClientConn
}

func NewFastFSClient(cc *grpc.ClientConn) FastFSClient {
	return &fastFSClient{cc}
}

func (c *fastFSClient) SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := c.cc.Invoke(ctx, "/api.FastFS/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastFSClient) OpenFile(ctx context.Context, in *OpenFileMessage, opts ...grpc.CallOption) (*OpenFileResponse, error) {
	out := new(OpenFileResponse)
	err := c.cc.Invoke(ctx, "/api.FastFS/OpenFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fastFSClient) ListFiles(ctx context.Context, in *FileQuery, opts ...grpc.CallOption) (*FileListResponse, error) {
	out := new(FileListResponse)
	err := c.cc.Invoke(ctx, "/api.FastFS/ListFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FastFSServer is the server API for FastFS service.
type FastFSServer interface {
	SayHello(context.Context, *PingMessage) (*PingMessage, error)
	OpenFile(context.Context, *OpenFileMessage) (*OpenFileResponse, error)
	ListFiles(context.Context, *FileQuery) (*FileListResponse, error)
}

func RegisterFastFSServer(s *grpc.Server, srv FastFSServer) {
	s.RegisterService(&_FastFS_serviceDesc, srv)
}

func _FastFS_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastFSServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FastFS/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastFSServer).SayHello(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastFS_OpenFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenFileMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastFSServer).OpenFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FastFS/OpenFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastFSServer).OpenFile(ctx, req.(*OpenFileMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FastFS_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FastFSServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.FastFS/ListFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FastFSServer).ListFiles(ctx, req.(*FileQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _FastFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.FastFS",
	HandlerType: (*FastFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _FastFS_SayHello_Handler,
		},
		{
			MethodName: "OpenFile",
			Handler:    _FastFS_OpenFile_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _FastFS_ListFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
